### ISSUE TITLE
Run one application using puppeteer,  but an error is no usable sandbox

### ISSUE THREAD

**Issue by xinfeingxia85** [bottlerocket-os/bottlerocket#1982]
We are planning to change os to Bottlerocket on AWS EKS, but some pods can't work fine and exit because of errors.
Having a service uses a puppeteer library,  and it always restarts but success.
We looked at the log and found that the sandbox was missing. 

**Platform I'm building on:**
```
K8s version: AWS EKS 1.21
Bottlerocket OS: latest
Runtime:  containerd
```

**What I expected to happen:**
We expect it can work fine with no errors.  

**What actually happened:**
It failed to run with the following error message.
```
(node:6) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0304/014020.516204:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5630fd1bd029 base::debug::CollectStackTrace()
#1 0x5630fd124623 base::debug::StackTrace::StackTrace()
#2 0x5630fd1378f0 logging::LogMessage::~LogMessage()
#3 0x5630fb24840b content::ZygoteHostImpl::Init()
#4 0x5630fccbed56 content::ContentMainRunnerImpl::Initialize()
#5 0x5630fccbcaa1 content::RunContentProcess()
#6 0x5630fccbd45e content::ContentMain()
#7 0x5630fcd1b7ce headless::HeadlessBrowserMain()
#8 0x5630fcd1b4fd headless::HeadlessShellMain()
#9 0x5630f9a62133 ChromeMain
#10 0x7fc37d4a42e1 __libc_start_main
#11 0x5630f9a61f6a _start

Received signal 6
#0 0x5630fd1bd029 base::debug::CollectStackTrace()
#1 0x5630fd124623 base::debug::StackTrace::StackTrace()
#2 0x5630fd1bcb01 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7fc381c150e0 (/lib/x86_64-linux-gnu/libpthread-2.24.so+0x110df)
#4 0x7fc37d4b6fff gsignal
#5 0x7fc37d4b842a abort
#6 0x5630fd1bbd95 base::debug::BreakDebuggerAsyncSafe()
#7 0x5630fd137d1f logging::LogMessage::~LogMessage()
#8 0x5630fb24840b content::ZygoteHostImpl::Init()
#9 0x5630fccbed56 content::ContentMainRunnerImpl::Initialize()
#10 0x5630fccbcaa1 content::RunContentProcess()
#11 0x5630fccbd45e content::ContentMain()
#12 0x5630fcd1b7ce headless::HeadlessBrowserMain()
#13 0x5630fcd1b4fd headless::HeadlessShellMain()
#14 0x5630f9a62133 ChromeMain
#15 0x7fc37d4a42e1 __libc_start_main
#16 0x5630f9a61f6a _start
  r8: 0000000000000000  r9: 00007ffe28241950 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffe28242c10 r13: 00007ffe28241ba0 r14: 00007ffe28242c20 r15: aaaaaaaaaaaaaaaa
  di: 0000000000000002  si: 00007ffe28241950  bp: 00007ffe28241b90  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fc37d4b6fff  sp: 00007ffe282419c8
  ip: 00007fc37d4b6fff efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:219:68)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**How to reproduce the problem:**
Deploy the Deployment on an EKS cluster running K8s 1.21 and use managed node group.
There are no other special requirements.

**Comment by gthao313** [comment]
Thanks for opening this issue. We're investigating on it and will get back to you.

**Comment by xinfeingxia85** [comment]
> Thanks for opening this issue. We're investigating on it and will get back to you.

Thank you. Looking forward to reply.

**Comment by bcressey** [comment]
Based on the puppeteer docs, it looks like it might require user namespaces. Those are disabled by default on Bottlerocket, because it increases the surface area in the kernel that can be reached by otherwise unprivileged users. However you can enable them if needed.

To enable via user data at VM launch:
```
[settings.kernel.sysctl]
"user.max_user_namespaces" = "16384"
```

To enable via apiclient from the control or admin container:
```
apiclient set -j '{"settings":{"kernel":{"sysctl":{"user.max_user_namespaces":"16384"}}}}'
```

Can you try that and see if it helps?

**Comment by xinfeingxia85** [comment]
> 

OK，i will verify and feedback the result as soon as possible.

Thank you.

**Comment by xinfeingxia85** [comment]
> Based on the puppeteer docs, it looks like it might require user namespaces. Those are disabled by default on Bottlerocket, because it increases the surface area in the kernel that can be reached by otherwise unprivileged users. However you can enable them if needed.
> 
> To enable via user data at VM launch:
> 
> ```
> [settings.kernel.sysctl]
> "user.max_user_namespaces" = "16384"
> ```
> 
> To enable via apiclient from the control or admin container:
> 
> ```
> apiclient set -j '{"settings":{"kernel":{"sysctl":{"user.max_user_namespaces":"16384"}}}}'
> ```
> 
> Can you try that and see if it helps?

I have verified that it works fine.  
Thank you.

**Comment by cbgbt** [comment]
Thanks!

**Comment by sameeraksc** [comment]
Thanks
